### ISSUE TITLE
Abandon/Delete this one?

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore-extensions/tagfield#1]
@Hagith nothing happens here, delete this one? is it on packagist, if so abandon?

**Comment by dpfaffenbauer** [comment]
ping @Hagith

**Comment by Hagith** [comment]
Yes, it is abandoned code. But maybe someday, someone will find this useful. It even has one fork ;)
IMHO we can just keep it forever here ;)

**Comment by dpfaffenbauer** [comment]
Right,  it should be marked as abandoned anyway. Even on packagist

**Comment by Hagith** [comment]
Added note in description. It was not published on packagist.
